FROM node:16.3.0 as builder
WORKDIR /weight-tracker

COPY frontend/package.json .
COPY frontend/package-lock.json .
RUN npm i

COPY frontend .

RUN npm run build

FROM nginx:1.23.3
WORKDIR /weight-tracker
RUN rm /etc/nginx/conf.d/default.conf

COPY --from=builder /weight-tracker/build .
