openapi: 3.0.3
info:
  title: Weight Tracker API
  version: 1.0.0
  description: Tracker for weight and other metrics of body
paths:
  /api/user_goals/:
    get:
      operationId: user_goals_list
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      tags:
      - user_goals
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedUserGoalList'
          description: ''
    post:
      operationId: user_goals_create
      tags:
      - user_goals
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserGoalCreateUpdate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserGoalCreateUpdate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserGoalCreateUpdate'
        required: true
      security:
      - cookieAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserGoalCreateUpdate'
          description: ''
  /api/user_goals/{id}/:
    put:
      operationId: user_goals_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - user_goals
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserGoalCreateUpdate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserGoalCreateUpdate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserGoalCreateUpdate'
        required: true
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserGoalCreateUpdate'
          description: ''
    patch:
      operationId: user_goals_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - user_goals
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedUserGoalCreateUpdate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedUserGoalCreateUpdate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedUserGoalCreateUpdate'
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserGoalCreateUpdate'
          description: ''
    delete:
      operationId: user_goals_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - user_goals
      security:
      - cookieAuth: []
      responses:
        '204':
          description: No response body
  /api/user_metrics/:
    get:
      operationId: user_metrics_list
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      tags:
      - user_metrics
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedUserMetricsList'
          description: ''
    post:
      operationId: user_metrics_create
      tags:
      - user_metrics
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserMetricsCreateUpdate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserMetricsCreateUpdate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserMetricsCreateUpdate'
        required: true
      security:
      - cookieAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserMetricsCreateUpdate'
          description: ''
  /api/user_metrics/{id}/:
    put:
      operationId: user_metrics_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - user_metrics
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserMetricsCreateUpdate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/UserMetricsCreateUpdate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UserMetricsCreateUpdate'
        required: true
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserMetricsCreateUpdate'
          description: ''
    patch:
      operationId: user_metrics_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - user_metrics
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedUserMetricsCreateUpdate'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedUserMetricsCreateUpdate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedUserMetricsCreateUpdate'
      security:
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserMetricsCreateUpdate'
          description: ''
    delete:
      operationId: user_metrics_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - user_metrics
      security:
      - cookieAuth: []
      responses:
        '204':
          description: No response body
components:
  schemas:
    GoalTypeEnum:
      enum:
      - local
      - global
      type: string
    PaginatedUserGoalList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/UserGoal'
    PaginatedUserMetricsList:
      type: object
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/UserMetrics'
    PatchedUserGoalCreateUpdate:
      type: object
      properties:
        user:
          type: integer
        weight_goal:
          type: integer
          maximum: 2147483647
          minimum: 0
          title: Ожидаемый вес (кг)
        goal_type:
          allOf:
          - $ref: '#/components/schemas/GoalTypeEnum'
          title: Тип цели
        target_date:
          type: string
          format: date
          nullable: true
          title: Дата ожидаемого результата
    PatchedUserMetricsCreateUpdate:
      type: object
      properties:
        user:
          type: integer
        weight:
          type: integer
          maximum: 2147483647
          minimum: 0
          title: Вес (кг)
        waist_circumference:
          type: integer
          maximum: 2147483647
          minimum: 0
          nullable: true
          title: Обхват талии
        measurement_date:
          type: string
          format: date
          title: Дата измерения
    UserGoal:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        user_id:
          type: integer
          title: Пользователь
          readOnly: true
        weight_goal:
          type: integer
          readOnly: true
          title: Ожидаемый вес (кг)
        goal_type:
          allOf:
          - $ref: '#/components/schemas/GoalTypeEnum'
          readOnly: true
          title: Тип цели
        target_date:
          type: string
          format: date
          readOnly: true
          nullable: true
          title: Дата ожидаемого результата
      required:
      - goal_type
      - id
      - target_date
      - user_id
      - weight_goal
    UserGoalCreateUpdate:
      type: object
      properties:
        user:
          type: integer
        weight_goal:
          type: integer
          maximum: 2147483647
          minimum: 0
          title: Ожидаемый вес (кг)
        goal_type:
          allOf:
          - $ref: '#/components/schemas/GoalTypeEnum'
          title: Тип цели
        target_date:
          type: string
          format: date
          nullable: true
          title: Дата ожидаемого результата
      required:
      - goal_type
      - user
    UserMetrics:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        user_id:
          type: integer
          title: Пользователь
          readOnly: true
        weight:
          type: integer
          readOnly: true
          title: Вес (кг)
        waist_circumference:
          type: integer
          readOnly: true
          nullable: true
          title: Обхват талии
        measurement_date:
          type: string
          format: date
          readOnly: true
          title: Дата измерения
      required:
      - id
      - measurement_date
      - user_id
      - waist_circumference
      - weight
    UserMetricsCreateUpdate:
      type: object
      properties:
        user:
          type: integer
        weight:
          type: integer
          maximum: 2147483647
          minimum: 0
          title: Вес (кг)
        waist_circumference:
          type: integer
          maximum: 2147483647
          minimum: 0
          nullable: true
          title: Обхват талии
        measurement_date:
          type: string
          format: date
          title: Дата измерения
      required:
      - user
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
