# Generated by Django 4.1.5 on 2023-01-04 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.PositiveIntegerField(default=0, verbose_name="Вес")),
                (
                    "waist_circumference",
                    models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name="Обхват талии"),
                ),
                (
                    "measurement_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата измерения"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "метрика",
                "verbose_name_plural": "метрики",
            },
        ),
        migrations.CreateModel(
            name="UserGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight_goal",
                    models.PositiveIntegerField(default=0, verbose_name="Ожидаемый вес"),
                ),
                (
                    "target_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата ожидаемого результата"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "цель",
                "verbose_name_plural": "цели",
            },
        ),
    ]
