# Generated by Django 4.1.5 on 2023-01-05 20:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("weight_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergoal",
            name="goal_type",
            field=models.CharField(
                choices=[("local", "Локальная цель"), ("global", "Глобальная цель")],
                default=1,
                max_length=255,
                verbose_name="Тип цели",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="usergoal",
            name="target_date",
            field=models.DateField(
                blank=True, default=datetime.date.today, null=True, verbose_name="Дата ожидаемого результата"
            ),
        ),
        migrations.AlterField(
            model_name="usergoal",
            name="weight_goal",
            field=models.PositiveIntegerField(default=0, verbose_name="Ожидаемый вес (кг)"),
        ),
        migrations.AlterField(
            model_name="usermetrics",
            name="measurement_date",
            field=models.DateField(default=datetime.date.today, verbose_name="Дата измерения"),
        ),
        migrations.AlterField(
            model_name="usermetrics",
            name="weight",
            field=models.PositiveIntegerField(default=0, verbose_name="Вес (кг)"),
        ),
    ]
