# Generated by Django 4.1.5 on 2023-01-04 23:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("weight_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usergoal",
            name="target_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="Дата ожидаемого результата",
            ),
        ),
        migrations.AlterField(
            model_name="usergoal",
            name="weight_goal",
            field=models.PositiveIntegerField(default=0, verbose_name="Ожидаемый вес (кг)"),
        ),
        migrations.AlterField(
            model_name="usermetrics",
            name="measurement_date",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Дата измерения"),
        ),
        migrations.AlterField(
            model_name="usermetrics",
            name="weight",
            field=models.PositiveIntegerField(default=0, verbose_name="Вес (кг)"),
        ),
    ]
